# models.py
# peewee
# Another popular one: SQLAlchemy

from peewee import * 

db = SqliteDatabase('database.sqlite')

class Loan(Model):
	id = CharField()
	member_id = DecimalField()
	loan_amnt = DecimalField()
	funded_amnt = DecimalField()
	funded_amnt_inv = DecimalField()
	term = CharField()
	int_rate = CharField()	
	installment = DecimalField()
	grade = CharField()
	sub_grade = CharField()
	emp_title = CharField()
	emp_length = CharField()
	home_ownership = CharField()
	annual_inc = DecimalField()
	verification_status = CharField()
	issue_d = CharField()
	loan_status = CharField()
	pymnt_plan = CharField()
	purpose = CharField()
	zip_code = CharField()
	addr_state = CharField()
	dti = DecimalField()
	delinq_2yrs = DecimalField()
	earliest_cr_line = CharField()
	inq_last_6mths = DecimalField()
	mths_since_last_delinq = DecimalField()
	mths_since_last_record = DecimalField()
	open_acc = DecimalField()
	pub_rec	= DecimalField()
	revol_bal = DecimalField()
	revol_util = CharField()
	total_acc = DecimalField()
	initial_list_status = CharField()
	out_prncp = DecimalField()
	out_prncp_inv = DecimalField()
	total_pymnt	= DecimalField()
	total_pymnt_inv = DecimalField()
	total_rec_prncp = DecimalField()
	total_rec_int = DecimalField()
	total_rec_late_fee = DecimalField()
	recoveries = DecimalField()
	collection_recovery_fee = DecimalField()
	last_pymnt_d = CharField()
	last_pymnt_amnt = DecimalField()
	next_pymnt_d = CharField()
	last_credit_pull_d = CharField()
	collections_12_mths_ex_med = DecimalField()
	mths_since_last_major_derog = DecimalField()
	policy_code = DecimalField()
	annual_inc_joint = DecimalField()
	dti_joint = DecimalField()
	verification_status_joint = CharField()
	application_type = CharField()
	acc_now_delinq = DecimalField()
	tot_coll_amt = DecimalField()
	tot_cur_bal = DecimalField()
	open_acc_6m = DecimalField()
	open_il_6m = DecimalField()
	open_il_12m = DecimalField()
	open_il_24m = DecimalField()
	mths_since_rcnt_il = DecimalField()
	total_bal_il = DecimalField()
	il_util = DecimalField()
	open_rv_12m = DecimalField()
	open_rv_24m = DecimalField()
	max_bal_bc = DecimalField()
	all_util = DecimalField()
	total_rev_hi_lim = DecimalField()
	inq_fi = DecimalField()
	total_cu_tl = DecimalField()
	inq_last_12m = DecimalField()

	class Meta:
		database = db
		db_table = "loan"

